[package]
name = "uhyve"
version = "0.0.1"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
A Rust-based, unikernel hypervisor
"""

[dependencies]
log = "0.4"
env_logger = "0.5.10"
aligned_alloc = "0.1"
elf = "0.0.10"
libc = "0.2"
memmap = "0.6"
lazy_static = "1.1"
clap = "2"
raw-cpuid = "6.1"
kvm-ioctls = "0.*"
kvm-bindings = "0.*"

[dependencies.x86]
version = "0.*"
#default-features = false