[package]
name = "uhyve"
version = "0.0.2"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen>"]
license = "MIT/Apache-2.0"
keywords = ["hypervisor", "unikernel"]
categories = ["os"]
readme = "README.md"

description = """
A hypervisor for RustyHermit
"""

[badges]
travis-ci = { repository = "hermitcore/uhyve" }

[dependencies]
log = "0.4"
env_logger = "0.5"
aligned_alloc = "0.1"
elf = "0.0.10"
libc = "0.2"
memmap = "0.6"
lazy_static = "1.1"
clap = "2"
raw-cpuid = "6.1"
bitflags = "1.1"

[target.'cfg(target_os = "linux")'.dependencies.kvm-ioctls]
version = "0.*"

[target.'cfg(target_os = "linux")'.dependencies.kvm-bindings]
version = "0.*"

[dependencies.x86]
version = "0.*"
#default-features = false
